# Generated by Django 4.0.1 on 2022-01-31 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_sale_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='posioions',
            new_name='positions',
        ),
        migrations.AlterField(
            model_name='sale',
            name='created',
            field=models.DateTimeField(blank=True),
        ),
    ]
